# Generated by Django 2.2.4 on 2019-08-22 10:23

from django.db import migrations, models
import ege.models


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, upload_to=ege.models.image_folder),
        ),
    ]
