# Generated by Django 2.2.3 on 2019-08-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedtest',
            name='num_of_test',
            field=models.ManyToManyField(to='ege.ExamTest'),
        ),
    ]
