# Generated by Django 2.2.3 on 2019-08-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0002_submittedtest_num_of_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedtest',
            name='num_of_test',
            field=models.ManyToManyField(blank=True, to='ege.ExamTest'),
        ),
    ]
