# Generated by Django 2.2.4 on 2019-08-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0002_auto_20190822_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='table',
            field=models.TextField(blank=True, null=True),
        ),
    ]
