# Generated by Django 2.2.3 on 2019-08-18 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0003_auto_20190818_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submittedtest',
            name='num_of_test',
        ),
        migrations.AddField(
            model_name='submittedtest',
            name='num_of_test',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='ege.ExamTest'),
        ),
    ]
