# Generated by Django 2.2.4 on 2019-08-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0003_question_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='description',
        ),
        migrations.RemoveField(
            model_name='question',
            name='table',
        ),
        migrations.AddField(
            model_name='question',
            name='description1',
            field=models.TextField(max_length=500, null=True, verbose_name='Описание вопроса 1'),
        ),
        migrations.AddField(
            model_name='question',
            name='description2',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание вопроса 2'),
        ),
    ]
