# Generated by Django 2.2.3 on 2019-08-18 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0004_auto_20190818_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedtest',
            name='num_of_test',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='ege.ExamTest'),
        ),
    ]
