# Generated by Django 2.2.3 on 2019-08-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0004_auto_20190822_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submittedtest',
            name='date',
        ),
        migrations.AlterField(
            model_name='question',
            name='description1',
            field=models.TextField(max_length=1500, null=True, verbose_name='Описание вопроса 1'),
        ),
        migrations.AlterField(
            model_name='question',
            name='description2',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Описание вопроса 2'),
        ),
    ]
