# Generated by Django 2.2.3 on 2019-08-18 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0005_auto_20190818_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedtest',
            name='num_of_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ege.ExamTest'),
        ),
    ]
