# Generated by Django 2.2.3 on 2019-08-24 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0006_auto_20190824_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submittedtest',
            old_name='users',
            new_name='user',
        ),
    ]
