# Generated by Django 2.2.3 on 2019-08-18 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0007_auto_20190818_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name'], 'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
    ]
