# Generated by Django 2.2.3 on 2019-08-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0008_auto_20190818_1737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['id'], 'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterField(
            model_name='submittedtest',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
