# Generated by Django 2.2.3 on 2019-08-25 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0008_question_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedtest',
            name='question10',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='submittedtest',
            name='question11',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='submittedtest',
            name='question12',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='submittedtest',
            name='question13',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='submittedtest',
            name='question14',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='submittedtest',
            name='question15',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='submittedtest',
            name='question16',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='submittedtest',
            name='question17',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='submittedtest',
            name='question18',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='submittedtest',
            name='question19',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='submittedtest',
            name='question20',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='submittedtest',
            name='question4',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='submittedtest',
            name='question5',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='submittedtest',
            name='question6',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='submittedtest',
            name='question7',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='submittedtest',
            name='question8',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='submittedtest',
            name='question9',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='examtest',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ege.Subject'),
        ),
    ]
