# Generated by Django 2.2.3 on 2019-08-25 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0009_auto_20190825_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='audio_file',
        ),
        migrations.AlterField(
            model_name='examtest',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ege.Subject'),
        ),
    ]
