# Generated by Django 2.2.3 on 2019-08-25 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0010_auto_20190825_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['name'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
    ]
