# Generated by Django 2.2.3 on 2019-08-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0011_auto_20190825_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='order_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
