# Generated by Django 2.2.3 on 2019-08-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0017_auto_20190825_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description1',
            field=models.TextField(max_length=5000, null=True, verbose_name='Описание вопроса 1'),
        ),
        migrations.AlterField(
            model_name='question',
            name='description2',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Описание вопроса 2'),
        ),
    ]
